<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Claire, this is for you</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background: linear-gradient(135deg, #ff7b7b, #ffb6b6);
            color: #fff;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            text-align: center;
        }

        .confession-container {
            background-color: #fff;
            color: #333;
            padding: 40px;
            border-radius: 15px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
            width: 85%;
            max-width: 500px;
            position: relative;
        }

        .confession-container::before {
            content: '❤️';
            font-size: 50px;
            position: absolute;
            top: -30px;
            left: 50%;
            transform: translateX(-50%);
        }

        h1 {
            color: #f45d5d;
            font-size: 2.5rem;
            margin-bottom: 20px;
        }

        p {
            font-size: 1.2rem;
            margin-bottom: 20px;
        }

        textarea {
            width: 100%;
            height: 150px;
            padding: 15px;
            border-radius: 10px;
            border: 1px solid #f45d5d;
            font-size: 16px;
            margin-bottom: 20px;
            transition: 0.3s;
        }

        textarea:focus {
            outline: none;
            border-color: #ff7b7b;
            background-color: #ffe6e6;
        }

        button {
            background-color: #f45d5d;
            color: white;
            border: none;
            padding: 12px 25px;
            border-radius: 30px;
            font-size: 1.2rem;
            cursor: pointer;
            transition: 0.3s;
        }

        button:hover {
            background-color: #ff7b7b;
        }

        .heart {
            color: #ff7b7b;
            font-size: 30px;
            margin-top: 20px;
        }

        .confessions-list {
            margin-top: 30px;
            text-align: left;
            font-size: 1.1rem;
            color: #333;
            border-top: 2px dashed #f45d5d;
            padding-top: 20px;
        }

        .confession-item {
            background-color: #fff;
            color: #333;
            border: 1px solid #ff7b7b;
            padding: 10px;
            border-radius: 10px;
            margin-top: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

    </style>
</head>
<body>

    <div class="confession-container">
        <h1>Claire, this is for you</h1>
        <p>An undeniable love for you</p>
        
        <textarea id="confessionInput" placeholder="What is your confession? 💖"></textarea>
        <br>
        <button onclick="submitConfession()">Submit Your Confession</button>

        <div class="heart">❤️</div>

        <!-- Display Submitted Confessions -->
        <div id="confessionsList" class="confessions-list">
            <h3>Previous Confessions:</h3>
        </div>
    </div>

    <script>
        function submitConfession() {
            // Get the confession text from the textarea
            const confession = document.getElementById('confessionInput').value;

            // If the confession is not empty, display it
            if (confession.trim() !== "") {
                // Create a new confession item
                const confessionItem = document.createElement("div");
                confessionItem.classList.add("confession-item");
                confessionItem.innerHTML = confession;

                // Append the new confession item to the list of confessions
                document.getElementById("confessionsList").appendChild(confessionItem);

                // Clear the textarea
                document.getElementById('confessionInput').value = ""; 
            } else {
                alert("Please type a confession before submitting!");
            }
        }
    </script>

</body>
</html>
